name: Build container image

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * TUE"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_DESC: "Experimental arch-bootc POC image"
  IMAGE_KEYWORDS: "bootc,archlinux,arch"
  IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/230667510?s=400"
  BASE_IMAGE_NAME: "arch-atomic-edition"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - desktop: kde
            variant: standard

          - desktop: kde
            variant: surface

          - desktop: gnome
            variant: standard

          - desktop: gnome
            variant: surface

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "BASE_IMAGE_NAME=${BASE_IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Get current date
        id: date
        run: |
          echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - name: Set image name
        run: |
          if [ "${{ matrix.variant }}" = "surface" ]; then
            echo "IMAGE_NAME=${BASE_IMAGE_NAME}-${{ matrix.desktop }}-surface" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=${BASE_IMAGE_NAME}-${{ matrix.desktop }}" >> $GITHUB_ENV
          fi

      - name: Image Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.DEFAULT_TAG }}
            type=raw,value=${{ env.DEFAULT_TAG }}-{{date 'YYYYMMDD'}}
          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            containers.bootc=1

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          build-args: |
            DESKTOP=${{ matrix.desktop }}
            VARIANT=${{ matrix.variant }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          oci: true

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GHCR
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: sigstore/cosign-installer@v3.9.2

      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          IMAGE="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

          echo "Resolving digest for $IMAGE"
          DIGEST=$(skopeo inspect docker://$IMAGE --format '{{.Digest}}')

          FULL_IMAGE="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}@${DIGEST}"

          echo "Signing $FULL_IMAGE"
          cosign sign -y --key env://COSIGN_PRIVATE_KEY "$FULL_IMAGE"